#          应用基础配置
server:
  port: 9080
  servlet:
    context-path: /SpringBootApp
#apollo配置
app:
  id: qmqSpringbootApp
apollo:
  meta: http://120.77.96.42:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://120.77.96.42:8080/eureka/
    register-with-eureka: false
    fetch-registry: false
#    mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      table-underline: false
#      表前缀名设置
#      table-prefix:
  configuration:
#    表字段名映射改为驼峰（默认为下划线分隔）
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.qmq.springbootpoj
#redis配置
  redis:
    jedis:
      pool:
        max-active: 8
#        日志配置
logging:
  level:
    com:
      qmq:
        springbootpoj:
          controller: debug

